project:
  type: book

book:
  title: "Machine Learning for Mechanical Engineering"
  author: "Mark Fuge"
  date: "6/11/2025"
  page-navigation: true
  page-footer: "Machine Learning for Mechanical Engineers Â© 2025 by [Mark Fuge and IDEAL Lab Contributors](./index.qmd#sec-contributors) is licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
  chapters:
    - index.qmd
    - intro.qmd
    - part: part1/part1.qmd
      chapters: 
        - part1/mapping_problems_to_models.qmd
        - part1/evaluating_models.qmd
        - part1/designing_experiments.qmd
        - part1/taking_derivatives.qmd
        - part1/gradient_descent.qmd
        - part1/measuring_distributions.qmd
    - part: part2/part2.qmd
      chapters: 
        - part2/review_linear_models.qmd
        - part2/review_NNs.qmd
        - part2/regularization_NNs.qmd
        - part2/failure_modes_NNs.qmd
        - part2/generative_models_pushforward.qmd
        - part2/generative_models_stochastic.qmd
        - part2/probabilistic_models.qmd
        - part2/failure_modes_probabilistic_models.qmd
        - part2/kernel_methods.qmd
    - part: part3/part3.qmd
      chapters: 
        - part3/dealing_with_small_data.qmd
        - part3/transfer_learning.qmd
    - part: problems/problems.qmd
      chapters: 
        - problems/ps1.qmd
    - looking_forward.qmd
    - references.qmd
  appendices:
    - appendices/helpful_tooling.qmd
    - appendices/data_preparation.qmd
    - appendices/course_progression.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor:
  render-on-save: true

